[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@4.7.0 --activate",
  "yarn install"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn preview"
